# Generated by Django 5.2.2 on 2025-10-29 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('quality_badge', models.CharField(blank=True, max_length=20)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('director', models.CharField(blank=True, max_length=255)),
                ('cast', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Optional IMDb rating', max_digits=3, null=True)),
                ('download_url', models.URLField(blank=True)),
                ('download_options', models.JSONField(blank=True, default=list)),
                ('server_options', models.JSONField(blank=True, default=list)),
                ('trailer_url', models.URLField(blank=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Marks movie as a highlighted/latest entry on the home page')),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('quality', models.CharField(blank=True, choices=[('SD', 'SD (480p)'), ('HD', 'HD (720p)'), ('FHD', 'Full HD (1080p)'), ('UHD', '4K Ultra HD')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='movies', to='movies.category')),
            ],
            options={
                'ordering': ('-release_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
